# Generated by Django 4.1.4 on 2022-12-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dep_name',
            new_name='dep_names',
        ),
    ]
